# Matlab Arrays:- 

In [1]:
# Export the following array as variable name "vec" to a mat file:

In [2]:
from scipy import io
import numpy as np

arr = np.arange(10)

io.savemat('arr.mat', {"vec":arr})

In [3]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


# Import data from matlab format:- 

In [4]:
# loadmat()

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

io.savemat('arr.mat', {"vec": arr})

mydata = io.loadmat('arr.mat')

print(mydata)

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Sun Nov 10 18:29:40 2024', '__version__': '1.0', '__globals__': [], 'vec': array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])}


In [5]:
print(mydata['vec'])

[[ 0  1  2  3  4  5  6  7  8  9 10]]


In [6]:
mydata = io.loadmat('arr.mat', squeeze_me = True)

print(mydata['vec'])

[ 0  1  2  3  4  5  6  7  8  9 10]
